Fill out all fields for the Instance type
NucciTheBoss/nlxd pull request #17
Opened 2024-02-29 05:24 UTC by samuelallan72

This should completely cover the fields described in the api documentation for [GET /1.0/instances](https://documentation.ubuntu.com/lxd/en/latest/api/#/instances/instance_get).

Note that `restore` is documented there, but does not appear in actual responses (and shouldn't appear; this appears to be a docs issue).  I opened https://github.com/canonical/lxd/issues/12993 to report it.

Fixes #9

2024-03-04 18:29 UTC, TheSignPainter98 requested changes
This is coming along nicely! Here are a few things to consider, mostly nitpicks though

2024-03-04 18:29 UTC, TheSignPainter98 commented on src/client.rs
> +    /// Get a list of instance names
nit: missing full stop ;)

2024-03-04 18:29 UTC, TheSignPainter98 commented on src/instance.rs
> +#[serde(deny_unknown_fields)]
On second thoughts, I'm not sure whether we want to deny unknown fields here. If lxd gives us an extra field we don't recognise, I think it would be more future-proof to ignore it. Otherwise, I think we'd break our users' code because we haven't gotten around to adding the extra fields!

2024-03-04 18:29 UTC, TheSignPainter98 commented on src/instance.rs
> +    status_code: StatusCode,
These two field seem quite similar, it almost looks as though one could call some `instance.status.code()` to get `instance.status_code`!

2024-03-04 18:29 UTC, TheSignPainter98 commented on src/client.rs
> +    // TODO: enum for http codes - use serde_repr
I wonder whether an enum here might be overkill, just looking at `reqwest for inspiration, they use a `struct StatusCode(NonZeroU16)` here, I wonder this simpler route would suffice?

2024-03-04 18:29 UTC, TheSignPainter98 commented on src/client.rs
> +    /// Get an instance's by instance name.
nit: I think the wording could be simplified a little :P
```
/// Try to get an instance by its name.
```

2024-03-04 18:29 UTC, TheSignPainter98 commented on src/instance.rs
> +/// This is not for HTTP status codes.
nit: Just to maximise information available to the user, I think we can point them in the right direction here by making the second sentence read something like:
```rust
// For HTTP status codes see [`HttpStatusCode`]
```

Or instead, could the issue be side-stepped entirely by renaming this to `InstanceStatusCode`?

2024-03-04 18:29 UTC, TheSignPainter98 commented on src/instance.rs
> +pub enum InstanceStatus {
Should these variants include the status code? If every `StatusCode` appears alongside at most one `InstanceStatus`, perhaps we could encode these together? As in could we have something like this?
```rust
pub enum InstanceStatus {
    Running(RunningStatus),
    ...
}

pub enum RunningStatus {
    OperationCreated = 100,
    ...
}
```
I have a feeling some combinations of `(instance.status, instance.status_code)` may be impossible, e.g. `(InstanceStatus::Error, StatusCode::Success)`

2024-03-04 18:29 UTC, TheSignPainter98 commented on src/instance.rs
> +    config: HashMap<String, String>, // TODO: is config completely described - can we use a struct?
I think merging TODOs can be okay, but I'd prefer that we didn't merge a TODO with a question mark over it :P

2024-03-04 18:29 UTC, TheSignPainter98 commented on src/instance.rs
> +    expanded_devices: HashMap<String, Device>,
I'm not quite sure I follow, do we need to keep around both `devices` and `expanded_devices`? (Same for `config`)

2024-03-04 21:45 UTC, samuelallan72 commented on src/instance.rs
> +#[serde(deny_unknown_fields)]
IMHO we definitely want to deny unknown fields.  If lxd updates the api and begins giving an extra field, it would be a breaking change in the same manner as changing the type of a field, and we would need to update the type definition here appropriately.

2024-03-04 21:48 UTC, samuelallan72 commented on src/client.rs
> +    // TODO: enum for http codes - use serde_repr
I don't think it would be overkill - I was looking at the lxd rest api docs, and they make some strong assertions, like for error return types:

> HTTP code must be one of of 400, 401, 403, 404, 409, 412 or 500.

2024-03-04 22:19 UTC, samuelallan72 commented on src/instance.rs
> +    status_code: StatusCode,
Yeah it's weird, but that's what's returned in the api.   Ideally we would ignore the `status` field and parse the `status_code` into an enum.  Not sure if we can do that neatly with serde though.

2024-03-04 22:20 UTC, samuelallan72 commented on src/instance.rs
> +/// This is not for HTTP status codes.
Good idea, I've renamed it. :)

2024-03-04 22:28 UTC, samuelallan72 commented on src/instance.rs
> +pub enum InstanceStatus {
It appears that `status` is simple the string representation of `status_code`.  https://github.com/canonical/lxd/blob/main/shared/api/status_code.go

So the two fields are redundant.  I'll see how we can ignore the `status` field I think.

2024-03-04 22:30 UTC, samuelallan72 commented on src/instance.rs
> +#[serde(deny_unknown_fields)]
Although if we didn't use deny_unknown_fields, we could then ignore some fields that we didn't care about... hmmm :thinking:

2024-03-04 22:31 UTC, samuelallan72 commented on src/instance.rs
> +    status_code: StatusCode,
Yep, I'll merge them.

2024-03-04 22:34 UTC, samuelallan72 commented on src/instance.rs
> +    expanded_devices: HashMap<String, Device>,
I'm not sure.  It seems that the two could be different, and perhaps useful to know.  The docs say:

expanded_devices:
> Expanded devices (all profiles and local devices merged)

devices:
> Instance devices (see doc/instances.md)

So I guess one is the final consolidated list of devices given the profiles, etc., while the other is just the devices configured specifically for that instance.

2024-03-04 22:44 UTC, samuelallan72 commented on src/instance.rs
> +/// This is not for HTTP status codes.
Agreed, I've renamed it. :)

2024-03-04 22:49 UTC, samuelallan72 commented
Thanks @TheSignPainter98 , I fixed the docs where noted, and and merged status and status_code into a more complete instance status.  I also removed `deny_unknown_fields` for `Instance` because otherwise it would be messy to ignore the redundant status field.  I think I would prefer to retain `deny_unknown_fields` to ensure completeness, but I guess in the end it doesn't matter too much?

2024-03-24 23:19 UTC, samuelallan72 commented
moved to https://github.com/canonical/nlxd-rs/pull/14

2024-03-24 23:19 UTC, closed without merging